package com.charles.scamradar.app.recovery

import android.content.Context
import android.content.Intent
import androidx.core.content.FileProvider
import com.charles.scamradar.app.community.ReportSanitizer
import com.charles.scamradar.app.data.model.ScanResult
import com.google.gson.Gson
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale
import java.util.zip.ZipEntry
import java.util.zip.ZipOutputStream

class EvidenceBundler(private val context: Context) {

    fun bundle(scanResult: ScanResult): File {
        val dir = File(context.cacheDir, "evidence").apply { mkdirs() }
        val ts = SimpleDateFormat("yyyyMMdd_HHmmss", Locale.US).format(Date())
        val out = File(dir, "scamradar_evidence_$ts.zip")

        ZipOutputStream(FileOutputStream(out)).use { zip ->
            putText(zip, "verdict.json", Gson().toJson(scanResult))
            putText(zip, "message_original.txt", scanResult.originalMessage)
            putText(zip, "message_redacted.txt", ReportSanitizer.sanitize(scanResult.originalMessage).excerpt)
            putText(zip, "red_flags.txt", buildRedFlags(scanResult))
            putText(zip, "summary.md", buildSummary(scanResult))
            scanResult.urlMetadata?.let { meta ->
                putText(zip, "url_metadata.json", Gson().toJson(meta))
                val ssPath = meta.screenshotPath
                if (ssPath.isNotBlank()) {
                    val ss = File(ssPath)
                    if (ss.exists()) {
                        zip.putNextEntry(ZipEntry("page_screenshot.png"))
                        FileInputStream(ss).use { input ->
                            input.copyTo(zip)
                        }
                        zip.closeEntry()
                    }
                }
            }
        }
        return out
    }

    fun shareIntent(file: File): Intent {
        val uri = FileProvider.getUriForFile(context, "${context.packageName}.fileprovider", file)
        return Intent(Intent.ACTION_SEND).apply {
            type = "application/zip"
            putExtra(Intent.EXTRA_STREAM, uri)
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
        }
    }

    private fun putText(zip: ZipOutputStream, name: String, body: String) {
        zip.putNextEntry(ZipEntry(name))
        zip.write(body.toByteArray())
        zip.closeEntry()
    }

    private fun buildRedFlags(scanResult: ScanResult): String {
        if (scanResult.redFlags.isEmpty()) return "No red flags recorded."
        return buildString {
            scanResult.redFlags.forEach { flag ->
                appendLine("- ${flag.phrase}: ${flag.reason}")
            }
        }
    }

    private fun buildSummary(scanResult: ScanResult): String {
        val date = SimpleDateFormat("yyyy-MM-dd HH:mm zzz", Locale.getDefault()).format(Date(scanResult.timestamp))
        return buildString {
            appendLine("# ScamRadar Evidence Bundle")
            appendLine()
            appendLine("- **Scan time:** $date")
            appendLine("- **Verdict:** ${scanResult.verdict.name}")
            appendLine("- **Scam type:** ${scanResult.scamType.name.replace("_", " ")}")
            appendLine("- **Confidence:** ${(scanResult.confidence * 100).toInt()}%")
            appendLine("- **Classifier:** ${scanResult.classifierTier.name}")
            appendLine()
            appendLine("Generated by ScamRadar for use in bank disputes, police reports, or sharing with family.")
            appendLine()
            appendLine("This bundle contains the original message, a redacted version, the classifier verdict (JSON), the red flags identified, and (for URL scans) the captured page screenshot and metadata.")
        }
    }
}
