package com.charles.scamradar.app.recovery

import android.content.Context
import android.graphics.Color
import android.graphics.Paint
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import androidx.core.content.FileProvider
import com.charles.scamradar.app.community.ReportSanitizer
import com.charles.scamradar.app.data.model.ScanResult
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

class IncidentReportBuilder(private val context: Context) {

    data class BuildInput(
        val scanResult: ScanResult,
        val flow: RecoveryFlow,
        val completedStepIds: Set<String>,
        val notes: String,
    )

    fun buildPdf(input: BuildInput): File {
        val pdf = PdfDocument()
        val pageInfo = PdfDocument.PageInfo.Builder(PAGE_W, PAGE_H, 1).create()
        val page = pdf.startPage(pageInfo)
        val canvas = page.canvas
        var y = MARGIN + 32f

        val title = Paint().apply {
            color = Color.parseColor("#0B57D0")
            textSize = 22f
            typeface = Typeface.create(Typeface.SANS_SERIF, Typeface.BOLD)
            isAntiAlias = true
        }
        val header = Paint().apply {
            color = Color.parseColor("#111111")
            textSize = 14f
            typeface = Typeface.create(Typeface.SANS_SERIF, Typeface.BOLD)
            isAntiAlias = true
        }
        val body = Paint().apply {
            color = Color.parseColor("#222222")
            textSize = 11f
            typeface = Typeface.SANS_SERIF
            isAntiAlias = true
        }
        val small = Paint().apply {
            color = Color.parseColor("#555555")
            textSize = 9f
            typeface = Typeface.SANS_SERIF
            isAntiAlias = true
        }

        canvas.drawText("ScamRadar Incident Report", MARGIN, y, title)
        y += 28f

        val ts = SimpleDateFormat("yyyy-MM-dd HH:mm", Locale.getDefault()).format(Date())
        canvas.drawText("Generated $ts (local time)", MARGIN, y, small)
        y += 18f

        canvas.drawText("Verdict", MARGIN, y, header)
        y += 16f
        canvas.drawText("${input.scanResult.verdict.name} — ${(input.scanResult.confidence * 100).toInt()}% confidence", MARGIN, y, body)
        y += 14f
        canvas.drawText("Scam type: ${input.scanResult.scamType.name.replace("_", " ")}", MARGIN, y, body)
        y += 14f
        canvas.drawText("Classifier: ${input.scanResult.classifierTier.name}", MARGIN, y, body)
        y += 22f

        canvas.drawText("Redacted message excerpt", MARGIN, y, header)
        y += 16f
        val sanitized = ReportSanitizer.sanitize(input.scanResult.originalMessage)
        y = drawWrapped(canvas, sanitized.excerpt, MARGIN, y, body, PAGE_W - 2 * MARGIN)
        y += 16f

        if (input.scanResult.redFlags.isNotEmpty()) {
            canvas.drawText("Red flags found", MARGIN, y, header)
            y += 16f
            input.scanResult.redFlags.forEachIndexed { idx, flag ->
                y = drawWrapped(canvas, "• ${flag.phrase} — ${flag.reason}", MARGIN, y, body, PAGE_W - 2 * MARGIN)
                if (y > PAGE_H - MARGIN) return@forEachIndexed
            }
            y += 10f
        }

        canvas.drawText("Recovery checklist", MARGIN, y, header)
        y += 16f
        input.flow.steps.forEach { step ->
            if (y > PAGE_H - MARGIN - 30f) return@forEach
            val mark = if (step.id in input.completedStepIds) "[x]" else "[ ]"
            y = drawWrapped(canvas, "$mark ${step.title}", MARGIN, y, body, PAGE_W - 2 * MARGIN)
            y = drawWrapped(canvas, "    ${step.description}", MARGIN, y, small, PAGE_W - 2 * MARGIN)
            y += 6f
        }

        if (input.notes.isNotBlank() && y < PAGE_H - MARGIN - 40f) {
            y += 10f
            canvas.drawText("Notes", MARGIN, y, header)
            y += 16f
            y = drawWrapped(canvas, input.notes, MARGIN, y, body, PAGE_W - 2 * MARGIN)
        }

        canvas.drawText(
            "Generated by ScamRadar. Verdict is automated and does not constitute legal advice.",
            MARGIN, PAGE_H - 12f, small,
        )

        pdf.finishPage(page)

        val dir = File(context.cacheDir, "incidents").apply { mkdirs() }
        val out = File(dir, "incident_${System.currentTimeMillis()}.pdf")
        FileOutputStream(out).use { pdf.writeTo(it) }
        pdf.close()
        return out
    }

    fun shareIntent(file: File): android.content.Intent {
        val uri = FileProvider.getUriForFile(context, "${context.packageName}.fileprovider", file)
        return android.content.Intent(android.content.Intent.ACTION_SEND).apply {
            type = "application/pdf"
            putExtra(android.content.Intent.EXTRA_STREAM, uri)
            addFlags(android.content.Intent.FLAG_GRANT_READ_URI_PERMISSION)
        }
    }

    private fun drawWrapped(
        canvas: android.graphics.Canvas,
        text: String,
        x: Float,
        startY: Float,
        paint: Paint,
        maxWidth: Float,
    ): Float {
        val words = text.split(" ")
        val line = StringBuilder()
        var y = startY
        words.forEach { word ->
            val tentative = if (line.isEmpty()) word else "${line} $word"
            if (paint.measureText(tentative) > maxWidth && line.isNotEmpty()) {
                canvas.drawText(line.toString(), x, y, paint)
                y += paint.textSize + 4f
                line.clear()
                line.append(word)
            } else {
                line.clear().append(tentative)
            }
        }
        if (line.isNotEmpty()) {
            canvas.drawText(line.toString(), x, y, paint)
            y += paint.textSize + 4f
        }
        return y
    }

    companion object {
        private const val PAGE_W = 595
        private const val PAGE_H = 842
        private const val MARGIN = 40f
    }
}
